stages:
 - build
 - test

test:branch:
  stage: test
  image: golang:1.11.0-alpine
  before_script:
    - apk update && apk add git make
    - mkdir -p /go/src/github.com/samsung-cnct/
    - ln -s /builds/user /go/src/github.com/samsung-cnct/cluster-manager-api
  script:
    - cd /go/src/github.com/samsung-cnct/cluster-manager-api
    - make -f build/Makefile install-dep dep-ensure
    - go test $(go list ./... | grep -v /vendor/ | grep -v generated ) -v -coverprofile .testCoverage.txt

build:branch:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    IMAGE_URI: $CI_REGISTRY_IMAGE:branch-$CI_COMMIT_REF_NAME-$CI_JOB_ID
    DOCKER_DRIVER: overlay2
    #  DOCKER_HOST: tcp://localhost:2375
  before_script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build -t $IMAGE_URI -f build/docker/cluster-manager-api/Dockerfile .
    - docker push $IMAGE_URI

