type: chart
rootfs:
  - image: samsung_cnct/cluster-manager-api
    context: cluster-manager-api
    chart: cluster-manager-api
    value: image.repo
    dockerContext: .
configs:
  - chart: cluster-manager-api
    timeout: 600
    retries: 2
    release: cluster-manager-api
prod:
  doDeploy: none