---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ template "chartname" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  template:
    metadata:
      name: {{ template "fullname" . }}
      labels:
        app: {{ template "name" . }}
        release: "{{ .Release.Name }}"
    spec:
      serviceAccountName: {{ .Release.Name }}-serviceaccount
      containers:
      - name: {{ template "name" . }}
        image: "{{.Values.image.repo}}"
        imagePullPolicy: "Always"
        ports:
        - containerPort: {{.Values.service.port}}
        env:
        - name: CLUSTERMANAGERAPI_PORT
          value: "{{.Values.service.port}}"
