# Default values.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

name: cluster-manager-api 
image:
  repo: quay.io/samsung_cnct/cluster-manager-api:v0.0.4
#  tag: v0.0.4

service:
  port: 9050
